title: Elia Mascolo
url: "https://eliamascolo.github.io/"
baseurl: ""
remote_theme: pages-themes/architect@v0.2.0

plugins:
- jekyll-remote-theme

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/eliamascolo"
footer_text: "GitHub page"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "CV_Elia_Mascolo.pdf"
 - name: "Contact"
   link: "contact"
