title: Elia Mascolo
url: "https://eliamascolo.github.io/"
baseurl: ""
remote_theme: ankitsultana/researcher@gem

#plugins:
#- jekyll-remote-theme

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: "G-WL39373EB2"

footer: yes
footer_url: "https://github.com/eliamascolo"
footer_text: "GitHub page"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "research"
 - name: "CV"
   link: "CV_Elia_Mascolo.pdf"
 - name: "Communication and Teaching
   link: "comm_and_teaching"

